#!/usr/bin/env bash
# Generates deploy/compose/.env with random local secrets (K9: no secrets in the repository).
# Never overwrites an existing file, so re-running is always safe.
set -euo pipefail
cd "$(dirname "$0")"

if [[ -f .env ]]; then
  echo "deploy/compose/.env already exists; leaving it untouched."
  exit 0
fi

secret() { head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n'; }

umask 077
cat > .env <<EOT
# Generated by init-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Local use only; never commit.
POSTGRES_PASSWORD=$(secret)
ERP_PLATFORM_DB_PASSWORD=$(secret)
KEYCLOAK_DB_PASSWORD=$(secret)
KEYCLOAK_ADMIN_PASSWORD=$(secret)
EOT
echo "Created deploy/compose/.env"
